### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by domm** [act-psgi/Act#11] opened 2019-11-04 12:18 UTC
after the big merge, the test-suite is broken:

```
docker-compose run act /bin/bash
root@73f969ddcb96:/opt/act# prove -vlr t/
```

lots of fails (see below), most likely all related to missing/bad DB connection

```Test Summary Report
-------------------
t/02config.t       (Wstat: 3584 Tests: 40 Failed: 14)
  Failed tests:  25-38
  Non-zero exit status: 14
t/03database.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/04i18n.t         (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 34 tests but ran 1.
t/04template.t     (Wstat: 1536 Tests: 53 Failed: 6)
  Failed tests:  23-28
  Non-zero exit status: 6
t/06country.t      (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/08track.t        (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 7 tests but ran 0.
t/09dbbool.t       (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/10user.t         (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 52 tests but ran 0.
t/11talk.t         (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 21 tests but ran 0.
t/13participation.t (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 6 tests but ran 0.
t/14order.t        (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/15events.t       (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 7 tests but ran 0.
t/16timeslot.t     (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 8 tests but ran 0.
t/17invoice.t      (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
t/18abstract.t     (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: No plan found in TAP output
t/19news.t         (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/20tags.t         (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 15 tests but ran 0.
t/auth_password.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 20 tests but ran 0.
t/database.t       (Wstat: 1024 Tests: 9 Failed: 4)
  Failed tests:  3, 7-9
  Non-zero exit status: 4
t/dispatcher.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/image.t          (Wstat: 512 Tests: 2 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 4 tests but ran 2.
Files=28, Tests=1034, 17 wallclock secs ( 0.24 usr  0.05 sys + 12.88 cusr  1.23 csys = 14.40 CPU)
Result: FAIL

```

**Comment by HaraldJoerg** [comment] 2019-11-04 14:03
At least part of the problem is that `use Act::Config;` used to do an initial load of the global configuration.  The test files, and also the scripts in the bin directory, rely on that, so they mostly fail due to missing configuration entries.
As of b8b3d298fc4d390218af8ae84827dbbb5ed28984, Act::Config does no longer load the configuration, so either this needs to be partially reverted or all test files and bin scripts need to explicitly load the configuration.

**Comment by HaraldJoerg** [comment] 2019-11-04 14:57
Failures in 0418n.t, 04template.t, and dispatcher.t are caused by the new configuration variables general_dir_static and general_dir_conferences, which are missing in my configuration files  It seems that I would also need to rearrange my directory structure, so I'm awaiting a doc update.

**Comment by waterkip** [comment] 2019-11-04 23:19
The issue with the test is a missing test database. Most code looks for a test db which is found in t/lib/Act/Util.pm. I am contemplating to create an additional testdb in docker so we can run the tests there.

I am  torn between test the database or treat it as a blackbox. Pipelines would need to have a db in order to run.

**Comment by domm** [comment] 2019-11-05 10:36
I do suggest using a properly setup test db.

Usually old Perl apps don't make it very easy to mock DB calls, and I have the feeling that some logic is indeed embedded in the DB (eg not null fields, foreign key reference).

Generally I do this by either creating a cleaned out db-dump, or by starting from a fresh db and running some base fixtures. I also usually run the tests in one transaction per test file, so each file can have a clean / well-known DB.

**Comment by waterkip** [comment] 2019-11-06 04:52
I'm still on the fench about actual DB testing, I agree that it should be tested, but then we should create an alternative for what we have right now. I'll open another issue for that discussion.

I've submitted #22 to fix most of the issues regarding the tests, there are some things failing. I think the testsuite wants to have a couple of things I didn't need to have to get Act running with Docker. So if people are willing to look at the remaining issues, that would be great.

**Comment by HaraldJoerg** [comment] 2019-11-07 14:26
If it isn't possible to run the tests in a docker setup right now, then we should consider re-activating the good ol' evolution branch until this is settled.  The current master branch needs a different directory layout (plus more config/env variables) than the evolution-predecessors which are in use at Ilya's and domm's pilots., and it is not clear to me what steps are needed to migrate existing installations based on act-starter-debian.  I don't even have a DB-volume for act-db.

**Comment by waterkip** [comment] 2019-11-07 17:02
With one or two iterations we can fix these issues. We have four tests failing, coming from 21. I don't have time now or this weekend, but after I can pick up the remainder if they are still open.

If you could review #22, I would be very grateful.

**Comment by HaraldJoerg** [comment] 2019-11-07 17:58
I made some remarks from looking at the code - but note that currently I can't run the master branch with useful results because I have another directory layout which leads to false positives.

**Comment by waterkip** [comment] 2019-11-14 21:59
We seem to have this working now with #22. Please have another look. I think we can close this one after.

**Comment by HaraldJoerg** [comment] 2019-11-14 22:06
The dispatcher tests have just been skipped instead of being adapted to the changes in the code.  What's the plan here?

**Comment by waterkip** [comment] 2019-11-14 22:40
Good question. The short answer. It needs some love, but I wanted to see an OK from that test. The MR has been sitting there for over a week. I need some of the code to be merged to master.
It needs some loving to make it really pass in a next iteration.

The long answer:

I think the testsuite needs a big overhaul. Like you said in #23, there is too much deployment dependent stuf with Act. The whole testsuite is one big configuration checker and requires stuf to be there which can never be there if you just checkout the code. It needs work.

So..  we need to pick an approach. Do we want to keep the old style of testing, or are we actually testing Perl code? Or are we going to both, one which is just tests the code and another suite that does a bit more of integration testing, and run some happy day scenario based on a provided act.ini (which is why I wanted to inject act.ini's in the first place).

Because we are using DBIx::Class now I would like to move away from testing with a live DB and use Moo(se) roles to apply on a component and test functionality of each role where a component is a mocked/Moo(se)-y kind of thing. I'm willing to believe DBIx::Class can connect to a database and fetch the data based on some params. 

Another option is to move away from the current plack psgi thing and go for Mojo, Dancer or something similar. Why are we writing Plack? Maybe to big a thing for just fixing a testfile ;)

**Comment by HaraldJoerg** [comment] 2019-11-14 23:44
I'd really like to have the dispatcher and its test fixed before any new iteration is started.  The current dispatcher contains debugging warnings, two different mount points for user photos, and a second mount for private handlers where I'm really curious which URLs would end up there.  
The dispatcher does not need the database. The test file which works quite fine in the pre-merge branch shortcuts the connection call, and is also independent of act.ini contents.

**Comment by waterkip** [comment] 2019-11-15 11:05
I made them work.

**Comment by HaraldJoerg** [comment] 2019-11-15 12:03
Good work!

**Closed by HaraldJoerg** 2019-11-15 12:03 UTC
